ORG 0000H
LJMP MAIN
ORG 0013H ;ISR routine for no motion being detected
MOV A,#38H ;Initializing LCD
ACALL CW ;Calling command subroutine
ACALL DELAY ;Give LCD some time
MOV A,#0EH
ACALL CW
ACALL DELAY
MOV A,#01 ;Clearing LCD
ACALL CW
ACALL DELAY
MOV A,#06H ;Shifting cursor right
ACALL CW
ACALL DELAY
MOV A,#'M' ;Code to display "MOTION DETECTED" in LCD
ACALL DAT
ACALL DELAY
MOV A,#'O'
ACALL DAT
ACALL DELAY
MOV A,#'T '
ACALL DAT
ACALL DELAY
MOV A,#'I'
ACALL DAT
ACALL DELAY
MOV A,#'O'
ACALL DAT
ACALL DELAY
MOV A,#'N'
ACALL DAT
ACALL DELAY
MOV A,#' '
ACALL DAT
ACALL DELAY
MOV A,#'D'
ACALL DAT
ACALL DELAY
MOV A,#'E'
ACALL DAT
ACALL DELAY
MOV A,#'T'
ACALL DAT
ACALL DELAY
MOV A,#'E'
ACALL DAT
ACALL DELAY
MOV A,#'C'
ACALL DAT
ACALL DELAY
MOV A,#'T'
ACALL DAT
ACALL DELAY
MOV A,#'E'
ACALL DAT
ACALL DELAY
MOV A,#'D'
ACALL DAT
ACALL DELAY
RETI
ORG 0200H
MAIN: MOV IE, #10000100B ;low level triggered INT1 interrupt
STAY: JNB P3.3, STAY ;Checking status of INT1 pin to determine presence of motion
MOV A,#38H
ACALL CW
ACALL DELAY
MOV A,#0EH
ACALL CW
ACALL DELAY
MOV A,#01
ACALL CW
ACALL DELAY
MOV A,#06H
ACALL CW
ACALL DELAY
MOV A,#'M' ;Code to display "NO MOTION" on LCD
ACALL DAT
ACALL DELAY
MOV A,#'N'
ACALL DAT
ACALL DELAY
MOV A,#'O'
ACALL DAT
ACALL DELAY
MOV A,#' '
ACALL DAT
ACALL DELAY
MOV A,#'M'
ACALL DAT
ACALL DELAY
MOV A,#'O'
ACALL DAT
ACALL DELAY
MOV A,#'T '
ACALL DAT
ACALL DELAY
MOV A,#'I'
ACALL DAT
ACALL DELAY
MOV A,#'O'
ACALL DAT
ACALL DELAY
MOV A,#'N'
ACALL DAT
ACALL DELAY
SJMP MAIN
CW: MOV P1,A ;Command subroutine
CLR P2.0 ;RS is cleared to represent command and R/W is always 0 for write
SETB P2.1
ACALL DELAY
CLR P2.1 ;H-to-L pulse in Enable
RET
DAT: MOV P1,A ;Data subroutine
SETB P2.0 ;RS is set to represent data
SETB P2.1
ACALL DELAY
CLR P2.1 ;H-to-L in Enable
RET
DELAY: MOV R3,#10
HERE1: MOV R4,#255
HERE: DJNZ R4, HERE
DJNZ R3, HERE1
RET
END